#!/bin/sh

DESC="Push service daemon"
NAME=pushd
DAEMON=/usr/bin/$NAME
SCRIPTNAME=/etc/init.d/$NAME

[ -x "$DAEMON" ] || exit 0

do_start() {
	PID=`pidof $NAME`
	[ -z "$PID" ] || return 1
	$DAEMON
	RETVAL=$?
	return "$RETVAL"
}

do_stop() {
	PID=`pidof $NAME`
	if [ -n "$PID" ]; then
		kill $PID
	fi
	return 0
}

prt_res() {
	RETVAL=$1

	case "$RETVAL" in
		0|1)
			echo "... done."
			RETVAL=0
			;;
		*)
			echo "... failed!"
			RETVAL=1
			;;
	esac

	return $RETVAL
}

case "$1" in
	start)
		echo "Starting $DESC" "$NAME"
		do_start
		prt_res $?
		;;
	stop)
		echo "Stopping $DESC" "$NAME"
		do_stop
		prt_res $?
		;;
	*)
		echo "Usage: $SCRIPTNAME {start|stop}" >&2
		exit 3
		;;
esac

